# -*- coding: utf-8 -*-
"""Calculadora teste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_wZgn9oqARJkhDPte4mLL-Cf8aC_KbS
"""

valor1 = input("digite um numero: \n")
valor1_float = float(valor1)
print()
op = input("Qual operação quer fazer? digite apenas o número."
"\n (1) Adição. \n (2) Subtração.\n (3) Multiplicaçao.\n (4) Divisão.\n  ")
op_convert = int(op)
print()
valor2 = input("digite um segundo numero: \n")
valor2_float = float(valor2)
print()
if op_convert == 1:
  print('Resultado da soma: ', valor1_float + valor2_float)
elif op_convert == 2:
  print('Resultado da subtração: ', valor1_float - valor2_float)
elif op_convert == 3:
  print('Resultado da multiplicação: ', valor1_float * valor2_float)
elif op_convert == 4:
  print('Resultado da divisão: ', valor1_float / valor2_float)